<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Test User',
                'email' => 'test@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-01-22 13:50:26',
                'password' => '$2y$12$jY/008x2ND58NcRyUVyUWOBOpE9mjyfCQZtynRFyKRNEEVq.Iq772',
                'remember_token' => 'G5N8lIpERx',
                'created_at' => '2026-01-22 13:50:27',
                'updated_at' => '2026-01-22 13:50:27',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Test Customer',
                'email' => 'testcustomer@example.com',
                'phone' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$fVbiB7DGB/WRMiwXLgip2O2rlb1whD4WZmNOtIgaquCKv7MXEndni',
                'remember_token' => NULL,
                'created_at' => '2026-01-24 19:45:54',
                'updated_at' => '2026-01-24 19:45:54',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'name' => 'Ally Rempel',
                'email' => 'janessa.treutel@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => '1R4soM5CEw',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'Francesca Zulauf',
                'email' => 'beer.ona@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'UqoOWdOMyy',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Samir Bednar',
                'email' => 'qstamm@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => '0VmiKArJcg',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Domenica Lueilwitz',
                'email' => 'ythiel@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'efeirbqoHO',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Dr. Maximus Bechtelar MD',
                'email' => 'lila42@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'I8wn8OQgP7',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Prof. Liam Ward',
                'email' => 'ygerhold@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'ccSYOrElpJ',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Prof. Malvina O\'Keefe',
                'email' => 'orobel@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'oWKZNrOYPL',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'Carmen Graham DDS',
                'email' => 'vkunde@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'tpurBSMa9w',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'Dr. Kobe Gutkowski',
                'email' => 'veum.gregoria@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'DTPwwbpe1x',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'Darrin Kiehn',
                'email' => 'gardner67@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'b9NAXwJ5TK',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'Garret Schneider MD',
                'email' => 'bauch.arnold@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'O6RnYBtQyx',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'Albin Simonis',
                'email' => 'rosenbaum.beverly@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'Y7YDdriwDb',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'Verda Mohr MD',
                'email' => 'efren.carter@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'JuyxwC4i9r',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'Marina Wehner',
                'email' => 'lulu.ward@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => '5UJGwFzHOS',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'Verda Lebsack',
                'email' => 'mateo73@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'eaexGEyN4a',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Ward Upton',
                'email' => 'turcotte.zula@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'oCRp9bI0tc',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'Caesar Gorczany',
                'email' => 'janae53@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 't71eDSEzxi',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'Mrs. Alfreda Hand',
                'email' => 'qnienow@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'HQXzACneEp',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'Ofelia Schmitt',
                'email' => 'borer.ruth@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => '4L2WcmROhc',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'Donald Zulauf',
                'email' => 'smurray@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:22:47',
                'password' => '$2y$12$c5fjMCFeZT.v48Oyy4fpiul4GkIhcvQoujF1p3guES/XFOUUnjdFq',
                'remember_token' => 'HHMZF1JJSy',
                'created_at' => '2026-02-24 09:22:47',
                'updated_at' => '2026-02-24 09:22:47',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'Ms. Name Rath',
                'email' => 'reanna.wilderman@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:31',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'Rb78MEYF33',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'Prof. Alda Thiel',
                'email' => 'erohan@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'DlzeKVTXGl',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'Heidi Hodkiewicz',
                'email' => 'lottie65@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'KbDi8EdGER',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'Estrella Hyatt',
                'email' => 'keven77@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'FTb9YzO16a',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'Jessika Kohler',
                'email' => 'berge.ruth@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'MAINEInCvz',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'Ms. Modesta Kreiger',
                'email' => 'stacy.crist@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'JZL8yvn1WO',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'Stewart Hammes',
                'email' => 'dhodkiewicz@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'ku0HmGJn0B',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'John Schimmel DDS',
                'email' => 'melba.kiehn@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'hfc2EK6e4U',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'Carmel Mitchell',
                'email' => 'halvorson.gus@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'IJAOudsNGe',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'Mrs. Annalise Kuhic Jr.',
                'email' => 'idaniel@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'cAbZ5v3Ohm',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'Janessa Skiles',
                'email' => 'jermain.hermann@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'eu2kwYftYy',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'Hertha Legros',
                'email' => 'abshire.marcia@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'OXYiFZTgYX',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'Sarina Lowe',
                'email' => 'wcummerata@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'ygoYt9kGAT',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'Otha Gusikowski Sr.',
                'email' => 'brielle.ward@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => '6WcedgqyYG',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'Prof. Dallas Gorczany DVM',
                'email' => 'seamus.lemke@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'JOjno3BdEL',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'Lennie Gerlach',
                'email' => 'morissette.dolly@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => '4iLGWbIrXk',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'Garland Aufderhar',
                'email' => 'korey.christiansen@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'nv8cKeRFi5',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'Loyce Kautzer',
                'email' => 'gusikowski.kenya@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'UwOaQ9yYx3',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'Nicolette Parker',
                'email' => 'halvorson.judd@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'BUwwRD0vlN',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'Ms. Lera Franecki',
                'email' => 'marquise.collins@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'JVrHjvm53G',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'Otto Murazik',
                'email' => 'trantow.karelle@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'Ui6nRXoZci',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'Precious Bartell',
                'email' => 'roxane.green@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'cfEqqcfxFx',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'Candace O\'Connell',
                'email' => 'zgislason@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'chA4da3lJo',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'Dr. Addison Waelchi MD',
                'email' => 'jacobs.jaeden@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'YogIac9Cti',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'Duane Spencer',
                'email' => 'fritsch.emilie@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'eecYC7Anfh',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'Delia McGlynn',
                'email' => 'wiza.chasity@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'xYWqb1GsUz',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'Prof. Maryam Dooley II',
                'email' => 'annabell.mann@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'fN85F3jyMG',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'Raquel Medhurst',
                'email' => 'pokeefe@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'uKC917g8Yv',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'Miss Audreanne Pouros',
                'email' => 'mcdermott.brown@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'CUy80l2wCj',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'Jermaine Hettinger',
                'email' => 'nathen.christiansen@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:23:32',
                'password' => '$2y$12$0KvF5nU1mubh5f.xtHcCNuVtup3XOrM6/E.NrDXI/lflMoA1YUO6C',
                'remember_token' => 'ou8J3adSFB',
                'created_at' => '2026-02-24 09:23:32',
                'updated_at' => '2026-02-24 09:23:32',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'Roel Stamm',
                'email' => 'uhowe@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'zfvoLPCpsb',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            53 => 
            array (
                'id' => 55,
                'name' => 'Ms. Freda Marquardt PhD',
                'email' => 'madelynn67@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'GOnl9Kw003',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            54 => 
            array (
                'id' => 56,
                'name' => 'Dean Wolf II',
                'email' => 'shakira38@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'RNCnKSUIp8',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            55 => 
            array (
                'id' => 57,
                'name' => 'Adan Leffler',
                'email' => 'deangelo25@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'PdAvPCLCf6',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'Mrs. Jacquelyn Hickle',
                'email' => 'madie.boyle@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'akp7LouBK3',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            57 => 
            array (
                'id' => 59,
                'name' => 'Mr. Triston Torp',
                'email' => 'dax.white@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'JblumKqx2H',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            58 => 
            array (
                'id' => 60,
                'name' => 'Ms. Helene Stehr I',
                'email' => 'harry96@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'ZKP5cGHXkY',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            59 => 
            array (
                'id' => 61,
                'name' => 'Corrine Lubowitz',
                'email' => 'mgreen@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'XkGW7XRvBe',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            60 => 
            array (
                'id' => 62,
                'name' => 'Dr. Ramiro Cummerata',
                'email' => 'stanford.quigley@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'eJctro9aE4',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            61 => 
            array (
                'id' => 63,
                'name' => 'Dr. Eddie Bechtelar III',
                'email' => 'oreilly.jakayla@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'CwgAfRJqza',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            62 => 
            array (
                'id' => 64,
                'name' => 'Bridgette Schmeler V',
                'email' => 'tabbott@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'WdW71DYE8Z',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            63 => 
            array (
                'id' => 65,
                'name' => 'Andres Strosin',
                'email' => 'gibson.destin@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'vw9vf5WaOb',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            64 => 
            array (
                'id' => 66,
                'name' => 'Nicklaus Bechtelar',
                'email' => 'moore.freeda@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'KBPDiizEQ6',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            65 => 
            array (
                'id' => 67,
                'name' => 'Triston Johns',
                'email' => 'fmoen@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'P8kQe92xUd',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            66 => 
            array (
                'id' => 68,
                'name' => 'Dameon Wintheiser',
                'email' => 'ritchie.wilfredo@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'fagz8XvcII',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            67 => 
            array (
                'id' => 69,
                'name' => 'Reid Schneider Sr.',
                'email' => 'eokeefe@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'YzRddMEFJY',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            68 => 
            array (
                'id' => 70,
                'name' => 'Horace Borer',
                'email' => 'vvon@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'J3vRujlHOE',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            69 => 
            array (
                'id' => 71,
                'name' => 'Prof. Holden Friesen',
                'email' => 'lucile17@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'LE44Nn9btG',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            70 => 
            array (
                'id' => 72,
                'name' => 'Jean Metz IV',
                'email' => 'raynor.grady@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'ugcSc4pBS9',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            71 => 
            array (
                'id' => 73,
                'name' => 'Zander Nicolas PhD',
                'email' => 'skemmer@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:13',
                'password' => '$2y$12$D63qi9VwVij6bWsYsfOY0.W1hBji0gCF0U8hXrkbayfpqB2bhO5GK',
                'remember_token' => 'qnJXOnxt0W',
                'created_at' => '2026-02-24 09:31:13',
                'updated_at' => '2026-02-24 09:31:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            72 => 
            array (
                'id' => 74,
                'name' => 'Aubree Flatley DDS',
                'email' => 'olin.johnson@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'WerqE79hK6',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            73 => 
            array (
                'id' => 75,
                'name' => 'Terrell Beatty',
                'email' => 'brown.reginald@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'iC0QSwn6KP',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            74 => 
            array (
                'id' => 76,
                'name' => 'Josue Spinka',
                'email' => 'torey.spencer@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'KBaKzR4acV',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            75 => 
            array (
                'id' => 77,
                'name' => 'Miss Dolly Hartmann',
                'email' => 'kris.michelle@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'H8ygLxy1tU',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            76 => 
            array (
                'id' => 78,
                'name' => 'Carlotta Dare',
                'email' => 'tito50@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'awQMfyF3qy',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            77 => 
            array (
                'id' => 79,
                'name' => 'Prof. Mathew Franecki I',
                'email' => 'lucy.runolfsson@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => '9Uvv4hILnO',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            78 => 
            array (
                'id' => 80,
                'name' => 'Velma Terry',
                'email' => 'aufderhar.augustine@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'qzWlNyl4z0',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            79 => 
            array (
                'id' => 81,
                'name' => 'Hester Corwin',
                'email' => 'rosalia.nader@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'PjEraJioW1',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            80 => 
            array (
                'id' => 82,
                'name' => 'Neva Lynch Sr.',
                'email' => 'hollis18@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'jK5bLjfgUt',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            81 => 
            array (
                'id' => 83,
                'name' => 'Prof. Monique Sipes IV',
                'email' => 'cgottlieb@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'k0IEoVURBm',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            82 => 
            array (
                'id' => 84,
                'name' => 'Mina Wisozk',
                'email' => 'zgibson@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'kRWRSolVOz',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            83 => 
            array (
                'id' => 85,
                'name' => 'Dr. Edwardo Ziemann DDS',
                'email' => 'jeffrey75@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'RqAaNZeZWo',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            84 => 
            array (
                'id' => 86,
                'name' => 'Gudrun Buckridge',
                'email' => 'karli30@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'xHPTqpJfD9',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            85 => 
            array (
                'id' => 87,
                'name' => 'Cale Spinka',
                'email' => 'jerry89@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'DDa3BkuKpR',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            86 => 
            array (
                'id' => 88,
                'name' => 'Suzanne Oberbrunner',
                'email' => 'greg12@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'sFWBycxARd',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            87 => 
            array (
                'id' => 89,
                'name' => 'Nicolas Torphy',
                'email' => 'initzsche@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'QEyo3kkdfj',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            88 => 
            array (
                'id' => 90,
                'name' => 'Assunta Leannon',
                'email' => 'thuels@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'gghq4kAshV',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            89 => 
            array (
                'id' => 91,
                'name' => 'Marc Pfannerstill',
                'email' => 'senger.theron@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'xf9jd9zxD0',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            90 => 
            array (
                'id' => 92,
                'name' => 'Laurie Runolfsson',
                'email' => 'kristy.krajcik@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'T1YpTccezT',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            91 => 
            array (
                'id' => 93,
                'name' => 'Demond Kuhic',
                'email' => 'qerdman@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:31:45',
                'password' => '$2y$12$JmQC08uc75w6/qwJTq20wuXDsUjHRWZ2vdhSKLjRqcTVIcWJ5gLC.',
                'remember_token' => 'hClRxaFDsc',
                'created_at' => '2026-02-24 09:31:45',
                'updated_at' => '2026-02-24 09:31:45',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            92 => 
            array (
                'id' => 94,
                'name' => 'Sandy Stroman II',
                'email' => 'crona.josiah@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'H7p4Sazw1w',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            93 => 
            array (
                'id' => 95,
                'name' => 'Collin Schimmel II',
                'email' => 'rempel.delphine@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'XUB9l6qnoD',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            94 => 
            array (
                'id' => 96,
                'name' => 'Ms. Janessa Miller IV',
                'email' => 'trantow.izabella@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'lUbta4XPH5',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            95 => 
            array (
                'id' => 97,
                'name' => 'Ms. Viva Schulist MD',
                'email' => 'janis.reichel@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'zPcAl2nxF2',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            96 => 
            array (
                'id' => 98,
                'name' => 'Mrs. Phoebe Ziemann II',
                'email' => 'lehner.darion@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'e4hpTZoCqF',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            97 => 
            array (
                'id' => 99,
                'name' => 'Brandyn Gottlieb',
                'email' => 'vpaucek@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => '0iqa3m0XFe',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            98 => 
            array (
                'id' => 100,
                'name' => 'Izaiah Gulgowski',
                'email' => 'skirlin@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'jKUQ1kjYoO',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            99 => 
            array (
                'id' => 101,
                'name' => 'Maurine Stanton',
                'email' => 'ike37@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'tnjRuHB0qz',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            100 => 
            array (
                'id' => 102,
                'name' => 'Miss Karina Boyle PhD',
                'email' => 'alfreda59@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'ubJ1hRay9J',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            101 => 
            array (
                'id' => 103,
                'name' => 'Kacey Skiles',
                'email' => 'fohara@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'l1QvfgSCD9',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            102 => 
            array (
                'id' => 104,
                'name' => 'Karine Treutel',
                'email' => 'little.xzavier@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'x5crF8W5Hj',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            103 => 
            array (
                'id' => 105,
                'name' => 'Dr. Kristy Zieme III',
                'email' => 'reggie71@example.org',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => '5ZEkBNv04h',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            104 => 
            array (
                'id' => 106,
                'name' => 'Kaleigh Mosciski',
                'email' => 'thompson.donnie@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'ZxbME7beVZ',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            105 => 
            array (
                'id' => 107,
                'name' => 'Ed Cole',
                'email' => 'orn.sandrine@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'gIGMoSBRl1',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            106 => 
            array (
                'id' => 108,
                'name' => 'Mrs. Samara Kemmer',
                'email' => 'erin.witting@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'qVoWYsu0Tf',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            107 => 
            array (
                'id' => 109,
                'name' => 'Berry Cummings Jr.',
                'email' => 'ihagenes@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'CH1wnpNH1z',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            108 => 
            array (
                'id' => 110,
                'name' => 'Domenico Leannon',
                'email' => 'lulu83@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'vrtAoh0Ev2',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            109 => 
            array (
                'id' => 111,
                'name' => 'Maximilian Kirlin',
                'email' => 'lia37@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'ZpfWqkqmtP',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            110 => 
            array (
                'id' => 112,
                'name' => 'Nia O\'Keefe Jr.',
                'email' => 'fletcher.kutch@example.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'FVKdaSD7qY',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            111 => 
            array (
                'id' => 113,
                'name' => 'Madisen Hudson DVM',
                'email' => 'istark@example.net',
                'phone' => NULL,
                'email_verified_at' => '2026-02-24 09:32:13',
                'password' => '$2y$12$Pf254GYGI3xLcChUsxA7I.5VxdlOnYjVi6aEp3cgJOfIRFXvSGzU6',
                'remember_token' => 'XJY7Zn4Rne',
                'created_at' => '2026-02-24 09:32:13',
                'updated_at' => '2026-02-24 09:32:13',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            112 => 
            array (
                'id' => 114,
                'name' => 'Super Admin',
                'email' => 'admin@sarafina.africa',
                'phone' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$lJtrf2VOOVf9M8uTqmxkV./ZwrAhhkHn4QW8hCFwmH9J0TFqgOVnW',
                'remember_token' => NULL,
                'created_at' => '2026-02-28 08:50:17',
                'updated_at' => '2026-02-28 12:14:57',
                'role' => 'admin',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => '2026-02-28 12:14:57',
            ),
            113 => 
            array (
                'id' => 115,
                'name' => 'Test User',
                'email' => 'samndlovucrypto1@gmail.com',
                'phone' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$8V3Sz/n.d1HZZQNh7x8SyOZqCqWjr7TWVYF5g3YJ10H5OfEf7C3BC',
                'remember_token' => NULL,
                'created_at' => '2026-02-28 10:13:28',
                'updated_at' => '2026-02-28 10:13:28',
                'role' => 'customer',
                'points_balance' => 0,
                'birthday' => NULL,
                'last_activity_at' => NULL,
            ),
            114 => 
            array (
                'id' => 116,
                'name' => 'Ndlovu Samuel',
                'email' => 'samndlovucrypto@gmail.com',
                'phone' => NULL,
                'email_verified_at' => '2026-02-28 11:05:25',
                'password' => '$2y$12$mz9d89qqe2mV9vzC4wQOF.UwwtKM1HrwigSQxvxrKEY.otMdNe/Zy',
                'remember_token' => NULL,
                'created_at' => '2026-02-28 11:05:04',
                'updated_at' => '2026-02-28 11:33:24',
                'role' => 'customer',
                'points_balance' => 170,
                'birthday' => NULL,
                'last_activity_at' => '2026-02-28 11:33:24',
            ),
        ));
        
        
    }
}